language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  on:
    all_branches: true
  edge: true
  provider: cloudfoundry
  username: jifa.wei@sas.com
  api: https://api.run.pivotal.io
  organization: jifwei
  space: staging
  password:
    secure: F63YC87sYnl806Zg6cyU8ZcaYr8BZIxyfPygDuZcVHgos/OLjO7k6fH05aqQ6qga6kCndaWP4umX2tiGu6avk4ELz6jhpfI6l+8OEpCdf3UdCyArC5uTaB53wE3AFkOcjKC7W/1yXliuO3ztfTOTAIwga7tZgug/OxHTj98ixnGgOt+VsAWsJC4+FqQBNLRHiPkKjqO4gxPoDrCbv50hhf4JHBcTm3qWdUDqfrswR8lnl0++162YdootXgo+rZmtZZq2fbGT8d49B+Wekrp+PGrRDjcpFCWdGJk76xNKE7erg3GFKPewuUwLJz3GeSE2u6dBSDdADdtUkhbItzdF3BvSWaRN9ykwIEK0Hzru2sYOboFjDYJOAbL5WITGHOOfVsCBATq9u75BErEiP+VSZpjIG2vg9l8VdSElMrzdp8riWfATfoBjJf7iLoPH+tMDXNnCna6Ezr+6Xhk1IHhhNkMk6YNEZ/njWHr970SUlE0k3+O4x86IzQ7BNyGjjKepzp805pdCpyhsZwX3hDEfoah+0fY0Ii3QlkAcCi7dN7EfPpHZQIJciczYi6rngqTw9JmB+PhmLWmLbd