language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  edge: true
  provider: cloudfoundry
  username: jifwei 
  api: https://api.run.pivotal.io
  organization: jifwei
  space: development